 
// <autogenerated>
// This is Launchark auto-generated code. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

using System;
using Liara.Common;

namespace Liara.RequestProcessing
{
    public sealed partial class LiaraRequestHeaderCollection
    {

        /// <summary> 
        /// Request Header: Accept
        /// </summary>
        public LiaraHeaderEntry Accept 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Accept");
            }
        }
                    
        /// <summary> 
        /// Request Header: Accept-Charset
        /// </summary>
        public LiaraHeaderEntry AcceptCharset 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Accept-Charset");
            }
        }
                    
        /// <summary> 
        /// Request Header: Accept-Encoding
        /// </summary>
        public LiaraHeaderEntry AcceptEncoding 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Accept-Encoding");
            }
        }
                    
        /// <summary> 
        /// Request Header: Accept-Language
        /// </summary>
        public LiaraHeaderEntry AcceptLanguage 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Accept-Language");
            }
        }
                    
        /// <summary> 
        /// Request Header: Accept-Datetime
        /// </summary>
        public LiaraHeaderEntry AcceptDatetime 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Accept-Datetime");
            }
        }
                    
        /// <summary> 
        /// Request Header: Authorization
        /// </summary>
        public LiaraHeaderEntry Authorization 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Authorization");
            }
        }
                    
        /// <summary> 
        /// Request Header: Cache-Control
        /// </summary>
        public LiaraHeaderEntry CacheControl 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Cache-Control");
            }
        }
                    
        /// <summary> 
        /// Request Header: Connection
        /// </summary>
        public LiaraHeaderEntry Connection 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Connection");
            }
        }
                    
        /// <summary> 
        /// Request Header: Cookie
        /// </summary>
        public LiaraHeaderEntry Cookie 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Cookie");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Length
        /// </summary>
        public LiaraHeaderEntry ContentLength 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Length");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-MD5
        /// </summary>
        public LiaraHeaderEntry ContentMD5 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-MD5");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Type
        /// </summary>
        public LiaraHeaderEntry ContentType 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Type");
            }
        }
                    
        /// <summary> 
        /// Request Header: Date
        /// </summary>
        public LiaraHeaderEntry Date 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Date");
            }
        }
                    
        /// <summary> 
        /// Request Header: Expect
        /// </summary>
        public LiaraHeaderEntry Expect 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Expect");
            }
        }
                    
        /// <summary> 
        /// Request Header: From
        /// </summary>
        public LiaraHeaderEntry From 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "From");
            }
        }
                    
        /// <summary> 
        /// Request Header: Host
        /// </summary>
        public LiaraHeaderEntry Host 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Host");
            }
        }
                    
        /// <summary> 
        /// Request Header: If-Match
        /// </summary>
        public LiaraHeaderEntry IfMatch 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "If-Match");
            }
        }
                    
        /// <summary> 
        /// Request Header: If-Modified-Since
        /// </summary>
        public LiaraHeaderEntry IfModifiedSince 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "If-Modified-Since");
            }
        }
                    
        /// <summary> 
        /// Request Header: If-None-Match
        /// </summary>
        public LiaraHeaderEntry IfNoneMatch 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "If-None-Match");
            }
        }
                    
        /// <summary> 
        /// Request Header: If-Range
        /// </summary>
        public LiaraHeaderEntry IfRange 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "If-Range");
            }
        }
                    
        /// <summary> 
        /// Request Header: If-Unmodified-Since
        /// </summary>
        public LiaraHeaderEntry IfUnmodifiedSince 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "If-Unmodified-Since");
            }
        }
                    
        /// <summary> 
        /// Request Header: Max-Forwards
        /// </summary>
        public LiaraHeaderEntry MaxForwards 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Max-Forwards");
            }
        }
                    
        /// <summary> 
        /// Request Header: Origin
        /// </summary>
        public LiaraHeaderEntry Origin 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Origin");
            }
        }
                    
        /// <summary> 
        /// Request Header: Pragma
        /// </summary>
        public LiaraHeaderEntry Pragma 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Pragma");
            }
        }
                    
        /// <summary> 
        /// Request Header: Proxy-Authorization
        /// </summary>
        public LiaraHeaderEntry ProxyAuthorization 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Proxy-Authorization");
            }
        }
                    
        /// <summary> 
        /// Request Header: Range
        /// </summary>
        public LiaraHeaderEntry Range 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Range");
            }
        }
                    
        /// <summary> 
        /// Request Header: Referer
        /// </summary>
        public LiaraHeaderEntry Referrer 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Referer");
            }
        }
                    
        /// <summary> 
        /// Request Header: TE
        /// </summary>
        public LiaraHeaderEntry TE 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "TE");
            }
        }
                    
        /// <summary> 
        /// Request Header: Upgrade
        /// </summary>
        public LiaraHeaderEntry Upgrade 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Upgrade");
            }
        }
                    
        /// <summary> 
        /// Request Header: User-Agent
        /// </summary>
        public LiaraHeaderEntry UserAgent 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "User-Agent");
            }
        }
                    
        /// <summary> 
        /// Request Header: Via
        /// </summary>
        public LiaraHeaderEntry Via 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Via");
            }
        }
                    
        /// <summary> 
        /// Request Header: Warning
        /// </summary>
        public LiaraHeaderEntry Warning 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Warning");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Requested-With
        /// </summary>
        public LiaraHeaderEntry XRequestedWith 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Requested-With");
            }
        }
                    
        /// <summary> 
        /// Request Header: DNT
        /// </summary>
        public LiaraHeaderEntry DNT 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "DNT");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Forwarded-For
        /// </summary>
        public LiaraHeaderEntry XForwardedFor 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Forwarded-For");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Forwarded-Proto
        /// </summary>
        public LiaraHeaderEntry XForwardedProto 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Forwarded-Proto");
            }
        }
                    
        /// <summary> 
        /// Request Header: Front-End-Https
        /// </summary>
        public LiaraHeaderEntry FrontEndHttps 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Front-End-Https");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-ATT-DeviceId
        /// </summary>
        public LiaraHeaderEntry XATTDeviceId 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-ATT-DeviceId");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Wap-Profile
        /// </summary>
        public LiaraHeaderEntry XWapProfile 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Wap-Profile");
            }
        }
                    
        /// <summary> 
        /// Request Header: Proxy-Connection
        /// </summary>
        public LiaraHeaderEntry ProxyConnection 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Proxy-Connection");
            }
        }
                    
    }
}