 
// <autogenerated>
// This is Launchark auto-generated code. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

using System;
using Liara.Common;

namespace Liara.ResponseProcessing
{
    public sealed partial class LiaraResponseHeaderCollection
    {

        /// <summary> 
        /// Request Header: Access-Control-Allow-Origin
        /// </summary>
        public LiaraHeaderEntry AccessControlAllowOrigin 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Access-Control-Allow-Origin");
            }
        }
                    
        /// <summary> 
        /// Request Header: Accept-Ranges
        /// </summary>
        public LiaraHeaderEntry AcceptRanges 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Accept-Ranges");
            }
        }
                    
        /// <summary> 
        /// Request Header: Age
        /// </summary>
        public LiaraHeaderEntry Age 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Age");
            }
        }
                    
        /// <summary> 
        /// Request Header: Allow
        /// </summary>
        public LiaraHeaderEntry Allow 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Allow");
            }
        }
                    
        /// <summary> 
        /// Request Header: Cache-Control
        /// </summary>
        public LiaraHeaderEntry CacheControl 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Cache-Control");
            }
        }
                    
        /// <summary> 
        /// Request Header: Connection
        /// </summary>
        public LiaraHeaderEntry Connection 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Connection");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Encoding
        /// </summary>
        public LiaraHeaderEntry ContentEncoding 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Encoding");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Language
        /// </summary>
        public LiaraHeaderEntry ContentLanguage 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Language");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Length
        /// </summary>
        public LiaraHeaderEntry ContentLength 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Length");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Location
        /// </summary>
        public LiaraHeaderEntry ContentLocation 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Location");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-MD5
        /// </summary>
        public LiaraHeaderEntry ContentMD5 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-MD5");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Disposition
        /// </summary>
        public LiaraHeaderEntry ContentDisposition 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Disposition");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Range
        /// </summary>
        public LiaraHeaderEntry ContentRange 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Range");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Type
        /// </summary>
        public LiaraHeaderEntry ContentType 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Type");
            }
        }
                    
        /// <summary> 
        /// Request Header: Date
        /// </summary>
        public LiaraHeaderEntry Date 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Date");
            }
        }
                    
        /// <summary> 
        /// Request Header: ETag
        /// </summary>
        public LiaraHeaderEntry ETag 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "ETag");
            }
        }
                    
        /// <summary> 
        /// Request Header: Expires
        /// </summary>
        public LiaraHeaderEntry Expires 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Expires");
            }
        }
                    
        /// <summary> 
        /// Request Header: Last-Modified
        /// </summary>
        public LiaraHeaderEntry LastModified 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Last-Modified");
            }
        }
                    
        /// <summary> 
        /// Request Header: Link
        /// </summary>
        public LiaraHeaderEntry Link 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Link");
            }
        }
                    
        /// <summary> 
        /// Request Header: Location
        /// </summary>
        public LiaraHeaderEntry Location 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Location");
            }
        }
                    
        /// <summary> 
        /// Request Header: P3P
        /// </summary>
        public LiaraHeaderEntry P3P 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "P3P");
            }
        }
                    
        /// <summary> 
        /// Request Header: Pragma
        /// </summary>
        public LiaraHeaderEntry Pragma 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Pragma");
            }
        }
                    
        /// <summary> 
        /// Request Header: Proxy-Authenticate
        /// </summary>
        public LiaraHeaderEntry ProxyAuthenticate 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Proxy-Authenticate");
            }
        }
                    
        /// <summary> 
        /// Request Header: Refresh
        /// </summary>
        public LiaraHeaderEntry Refresh 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Refresh");
            }
        }
                    
        /// <summary> 
        /// Request Header: Retry-After
        /// </summary>
        public LiaraHeaderEntry RetryAfter 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Retry-After");
            }
        }
                    
        /// <summary> 
        /// Request Header: Permanent
        /// </summary>
        public LiaraHeaderEntry Permanent 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Permanent");
            }
        }
                    
        /// <summary> 
        /// Request Header: Server
        /// </summary>
        public LiaraHeaderEntry Server 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Server");
            }
        }
                    
        /// <summary> 
        /// Request Header: Set-Cookie
        /// </summary>
        public LiaraHeaderEntry SetCookie 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Set-Cookie");
            }
        }
                    
        /// <summary> 
        /// Request Header: Status
        /// </summary>
        public LiaraHeaderEntry Status 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Status");
            }
        }
                    
        /// <summary> 
        /// Request Header: Strict-Transport-Security
        /// </summary>
        public LiaraHeaderEntry StrictTransportSecurity 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Strict-Transport-Security");
            }
        }
                    
        /// <summary> 
        /// Request Header: Trailer
        /// </summary>
        public LiaraHeaderEntry Trailer 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Trailer");
            }
        }
                    
        /// <summary> 
        /// Request Header: Transfer-Encoding
        /// </summary>
        public LiaraHeaderEntry TransferEncoding 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Transfer-Encoding");
            }
        }
                    
        /// <summary> 
        /// Request Header: Vary
        /// </summary>
        public LiaraHeaderEntry Vary 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Vary");
            }
        }
                    
        /// <summary> 
        /// Request Header: Via
        /// </summary>
        public LiaraHeaderEntry Via 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Via");
            }
        }
                    
        /// <summary> 
        /// Request Header: Warning
        /// </summary>
        public LiaraHeaderEntry Warning 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Warning");
            }
        }
                    
        /// <summary> 
        /// Request Header: WWW-Authenticate
        /// </summary>
        public LiaraHeaderEntry WWWAuthenticate 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "WWW-Authenticate");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Frame-Options
        /// </summary>
        public LiaraHeaderEntry XFrameOptions 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Frame-Options");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-XSS-Protection
        /// </summary>
        public LiaraHeaderEntry XXSSProtection 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-XSS-Protection");
            }
        }
                    
        /// <summary> 
        /// Request Header: Content-Security-Policy
        /// </summary>
        public LiaraHeaderEntry ContentSecurityPolicy 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "Content-Security-Policy");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Content-Security-Policy
        /// </summary>
        public LiaraHeaderEntry XContentSecurityPolicy 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Content-Security-Policy");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-WebKit-CSP
        /// </summary>
        public LiaraHeaderEntry XWebKitCSP 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-WebKit-CSP");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Content-Type-Options
        /// </summary>
        public LiaraHeaderEntry XContentTypeOptions 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Content-Type-Options");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-Powered-By
        /// </summary>
        public LiaraHeaderEntry XPoweredBy 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-Powered-By");
            }
        }
                    
        /// <summary> 
        /// Request Header: X-UA-Compatible
        /// </summary>
        public LiaraHeaderEntry XUACompatible 
        { 
            get 
            {
                return new LiaraHeaderEntry(this, "X-UA-Compatible");
            }
        }
                    
    }
}